### PR TITLE
Problem: the BEP template does not ask to specify solution criteria

### PR DESCRIPTION
**Pull request by ldmberman**
Solution: include the "Solution Criteria" section into the BEP template

### CODE REVIEW

**Comment by ttmc** [comment]
I think that talking about "solution criteria" is a bit abstract and hard to imagine. Maybe you could instead say something like, "a detailed explanation of the problem, along with details of what it would take to solve it."

**Comment by vrde** [comment]
That short memo is really interesting! Changing this BEP might take a bit of time, since it's part of the "costitution". I have some ideas to share with you, I need few more days.

**Comment by ttmc** [comment]
@ldmberman Yes I like the idea of a **Problem Breakdown** section. Would it replace the proposed **Solution Criteria** section?

**Comment by ldmberman** [comment]
@ttmc yes, it would be a replacement.

**Comment by ttmc** [comment]
@ldmberman Okay, maybe make that change and see what @vrde says.

**Pull request merged**
